export const AUTH_LOADING = 'AUTH_LOADING';
export const AUTH_ERROR = 'AUTH_ERROR';

export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const GET_USERINFO_SUCCESS = 'GET_USERINFO_SUCCESS';
export const CHANGE_USERINFO_SUCCESS = 'CHANGE_USERINFO_SUCCESS';
export const SENDFORM_SUCCESS = 'SENDFORM_SUCCESS';