export const LOADING = 'GETTING_TASKS';
export const ERROR = 'GET_TASKS_FAILURE';

export const GET_TASKS_SUCCESS = 'GET_TASKS_SUCCESS';

export const EDIT_TASK_SUCCESS = 'EDIT_TASKS_SUCCESS';

export const ADD_TASK_SUCCESS = 'ADD_TASKS_SUCCESS';
export const ADDING_TASK = 'ADDING_TASK';

export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
export const DELETE_TASKS_SUCCESS = 'DELETE_TASKS_SUCCESS';
export const REMOMVEING_TASKS = 'REMOMVEING_TASKS';

export const GET_TASK_SUCCESS = 'GET_TASK_SUCCESS';

export const CHANGE_TASK_STATUS_SUCCESS = 'CHANGE_TASK_STATUS_SUCCESS';
